---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'hub01.jferre.local/ee-minimal-rhel8:latest'
  #ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'

dependencies:
  galaxy: requirements.yml
  #python: requirements.txt
